# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 00:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='persona',
            old_name='nombre',
            new_name='nombres',
        ),
    ]
