# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 01:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20171118_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='domicilio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='telefono',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
